### PR TITLE
Implement `cc`-style env var reading

### LINKED ISSUE #116: CFLAGS getting ignored
Hello, because of the recent PR #115, CFLAGS from environment variables get ignored.

My specific use case / possible way to reproduce:
Add `fdk-aac-sys = "0.5.0"` as dependency. It links to internal Android libraries so it fails to build, however if you run `export CFLAGS="-U__ANDROID__"` before cargo ndk it will successfully compile. This works fine in 3.2.0, but breaks in 3.2.1.

Thank you.

### PR DESCRIPTION
**Pull request by bbqsrc**
Theoretically fixes #116.

@rib please let me know.

### CODE REVIEW

**Comment by rib** [comment]
Cool, the patch looks good to me - maybe @Marekkon5 can double check it works for them?

**Comment by rib** [comment]
Just smoke testing with build android-activity where I have modified one of the C++ files compiled to have:

```c
#if __ANDROID_API__ < 29
#error "foo"
#endif
```

then running with: `CXXFLAGS="-Wall" cargo ndk -t arm64-v8a -p 21 build --features=game-activity`

I can see that the `-Wall` is being added:

`"C:\\Users\\Robert\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++" "-O0" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "--target=aarch64-linux-android21" "-Wall" "-I" "game-activity-csrc" "-o" "C:\\Users\\Robert\\src\\android-activity\\target\\aarch64-linux-android\\debug\\build\\android-activity-da79bec16e3c5391\\out\\game-activity-csrc/game-activity/GameActivity.o" "-c" "game-activity-csrc/game-activity/GameActivity.cpp"`

but I'm a bit surprised that the command includes two `--target` arguments for some reason (though luckily it does seem to pick up the correct API level since I do hit my `#error` check)

**Comment by bbqsrc** [comment]
That’s bizarre. I’ll look into it

**Comment by Marekkon5** [comment]
I can confirm that in my project the latest version `cargo-ndk v3.2.1 (https://github.com/bbqsrc/cargo-ndk/?branch=feature/cc-style-env#4739779a)` works with my `export CFLAGS="-U__ANDROID__"`.

**Comment by rib** [comment]
I don't think your change is the culprit @bbqsrc - I also just checked with the current release of cargo-ndk and I see the same.

I guess it's the `cc` crate adding it - but I thought the cc crate avoided adding a --target if it saw that a --target was specified via user flags.

**Comment by rib** [comment]
I suppose it's OK if later --target arguments have higher precedence (that at least seems to be the case) but could be good to see if there's a way to stop the cc crate from adding the other --target argument

**Comment by bbqsrc** [comment]
But if it adds it do we even have to? lol

**Comment by rib** [comment]
Yeah, the argument that the cc crate adds doesn't include the API level at the end which we need.

**Comment by rib** [comment]
Instrumenting the cc crate then the default just gets added here, and there isn't an obvious way to avoid that:
https://github.com/rust-lang/cc-rs/blob/bf4f709765016a16d2f4966305d6c181bdf05325/src/lib.rs#L1858

So I think for now we just need to rely on the later target overriding the one passed by the `cc` crate automatically.

**Comment by bbqsrc** [comment]
Right. So it has accidentally been working due to flag order the entire time. So we carry on. 🙂

**Comment by Marekkon5** [comment]
Thanks for fixing and merging. Will you consider pushing to crates.io (since this in my case and possibly in other as well is breaking change)? Thank you.

**Comment by bbqsrc** [comment]
@Marekkon5 it is published now as 3.2.2

**Pull request merged**
