### PR TITLE
Create an abomination

### LINKED ISSUE #92: NDK r25 does not handle quoted parameters to clang on Windows
Running `cargo ndk -t x86_64 -p 33 build` gives me this error:
```cmd
[2023-03-11T17:32:51Z INFO  cargo_ndk::cli] Using NDK at path: C:\AndroidNDK (ANDROID_NDK_HOME)
[2023-03-11T17:32:51Z INFO  cargo_ndk::cli] NDK API level: 33
[2023-03-11T17:32:51Z INFO  cargo_ndk::cli] Building targets: x86_64
[2023-03-11T17:32:51Z INFO  cargo_ndk::cli] Building x86_64 (x86_64-linux-android)
   Compiling and2 v0.1.0 (C:\Users\Glenn\and2)
error: linking with `C:\AndroidNDK\toolchains\llvm\prebuilt\windows-x86_64\bin\x86_64-linux-android33-clang.cmd` failed: exit code: 255
  |
  = note: "C:\\AndroidNDK\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android33-clang.cmd" "-Wl,--version-script=C:\\Users\\Glenn\\AppData\\Local\\Temp\\rustcMmyczo\\list" "-m64" "C:\\Users\\Glenn\\AppData\\Local\\Temp\\rustcMmyczo\\symbols.o" "C:\\Users\\Glenn\\and2\\target\\x86_64-linux-android\\debug\\deps\\and2.220y3l223trvteix.rcgu.o" "C:\\Users\\Glenn\\and2\\target\\x86_64-linux-android\\debug\\deps\\and2.3izm99ra9qa3p8id.rcgu.o" "-Wl,--as-needed" "-L" "C:\\Users\\Glenn\\and2\\target\\x86_64-linux-android\\debug\\deps" "-L" "C:\\Users\\Glenn\\and2\\target\\debug\\deps" "-L" "C:\\Users\\Glenn\\and2\\target\\cargo-ndk\\libgcc-workaround" "-L" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib" "-Wl,-Bstatic" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libstd-3b76298062fcbb41.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libpanic_unwind-5c79ad5020a8a376.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libobject-c856ab6f9f61a0c8.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libmemchr-4330e4945024bd31.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libaddr2line-b743fb28f7e6f36b.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libgimli-3c967a14752063ee.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\librustc_demangle-de83573183ce509d.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libstd_detect-189990c033015975.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libhashbrown-4ac8e97124e072c7.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libminiz_oxide-c58c6d1c5b304afc.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libadler-4112d160f12e0da0.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\librustc_std_workspace_alloc-e50526c393c6b479.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libunwind-c0afb47c69be5adb.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libcfg_if-36bd188b5238bf89.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\liblibc-9c1c158f10c4615e.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\liballoc-ae67f691b53af35a.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\librustc_std_workspace_core-e9e3e381106ad9fb.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libcore-e3d2ffae725503a0.rlib" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib\\libcompiler_builtins-7de08890edb9a78a.rlib" "-Wl,-Bdynamic" "-ldl" "-llog" "-lunwind" "-ldl" "-lm" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "C:\\Users\\Glenn\\.rustup\\toolchains\\nightly-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-linux-android\\lib" "-o" "C:\\Users\\Glenn\\and2\\target\\x86_64-linux-android\\debug\\deps\\liband2.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: --version-script=C:\Users\Glenn\AppData\Local\Temp\rustcMmyczo\list"" was unexpected at this time.


error: could not compile `and2` due to previous error
[2023-03-11T17:33:05Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2023-03-11T17:33:05Z INFO  cargo_ndk::cli]
[2023-03-11T17:33:05Z INFO  cargo_ndk::cli]     rustup target install x86_64-linux-android
```
I'm on a x86_64 Windows 10 machine, and I have installed both Android SDK and Android NDK.

### PR DESCRIPTION
**Pull request by bbqsrc**
Fixes #92.

@TomieAi can you test this and let me know if it fixes your issue?

```
cargo install --git https://github.com/bbqsrc/cargo-ndk --branch feature/windows-r25-workaround
```

### CODE REVIEW

**Comment by bbqsrc** [comment]
Tested it on a number of major crates, it works.

**Comment by bbqsrc** [comment]
image

**Comment by rib** [comment]
Huge thanks for taking a look at this issue, this was a big pain for me recently!

Unfortunately it looks like this breaks setting the 'platform' / api level because Clang itself parses the name of the executable to pull out the api level from the name, such that `aarch64-linux-android29-clang` would have an api level 29.

I guess the hard link names should be defined based on `clang_suffix()`

**Comment by rib** [comment]
(maybe it works though since I suppose `Command::().spawn()` isn't like `exec` on Linux and so I suppose Clang should see the right name - my comment above was only based on reviewing the change, so I'm not entirely sure)

**Comment by bbqsrc** [comment]
Yeah it doesn't matter what the names are because it simply grabs the correct path and calls it via another environment variable.

Essentially it just maps the args and then calls whatever.cmd, which is still the original name. 🙂

**Comment by ScSofts** [comment]
My CARGO_HOME is set to F:\Cargo, and temp path is "C:\TEMP" haha
```bat
H:\rust\flashdrop>cargo ndk -t arm64-v8a build
[2023-05-10T12:41:32Z INFO  cargo_ndk::cli] Using NDK at path: D:\compiler\Android\ndk\25.0.8775105 (ANDROID_HOME)
[2023-05-10T12:41:32Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-05-10T12:41:32Z INFO  cargo_ndk::cli] Building targets: arm64-v8a
[2023-05-10T12:41:32Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"C:\\TEMP\\.tmpbaLHAs\\ar.exe"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: CrossesDevices, message: "
系统无法将文件移到不同的磁盘驱动器。" }', src\cargo.rs:140:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bbqsrc** [comment]
lol fucking Windows. I’ll fix today, thanks for reporting!

**Comment by ScSofts** [comment]
> lol fucking Windows. I’ll fix today, thanks for reporting!

Thank you very much 👍

**Comment by ScSofts** [comment]
I had set "TEMP" to "F:\TEMP",It seems to be working.
```
[2023-05-10T12:54:12Z INFO  cargo_ndk::cli] Using NDK at path: D:\compiler\Android\ndk\25.0.8775105 (ANDROID_HOME)
[2023-05-10T12:54:12Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-05-10T12:54:12Z INFO  cargo_ndk::cli] Building targets: arm64-v8a
[2023-05-10T12:54:12Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpAqdVa2\\ar.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpAqdVa2\\cc.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpAqdVa2\\cxx.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpAqdVa2\\ranlib.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpAqdVa2\\triple-ar.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpAqdVa2\\triple-linker.exe"
warning: unused manifest key: package.crate-type
   Compiling bytes v1.4.0
   Compiling cfg-if v1.0.0
   Compiling jni-sys v0.3.0
   Compiling cesu8 v1.1.0
   Compiling json v0.12.4
   Compiling memchr v2.5.0
   Compiling thiserror v1.0.40
   Compiling log v0.4.17
   Compiling combine v4.6.6
   Compiling jni v0.21.1
   Compiling flashdrop v0.1.0 (H:\rust\flashdrop)
    Finished dev [unoptimized + debuginfo] target(s) in 6.00s
```

However, I found no "libflashdrop.so" in target\aarch64-linux-android\debug.

When I tried to execute commnad ` cargo ndk -t arm64-v8a -o . build `, it failed again.

```
[2023-05-10T12:53:56Z INFO  cargo_ndk::cli] Using NDK at path: D:\compiler\Android\ndk\25.0.8775105 (ANDROID_HOME)
[2023-05-10T12:53:56Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-05-10T12:53:56Z INFO  cargo_ndk::cli] Building targets: arm64-v8a
[2023-05-10T12:53:56Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpADw0AH\\ar.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpADw0AH\\cc.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpADw0AH\\cxx.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpADw0AH\\ranlib.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpADw0AH\\triple-ar.exe"
Cargo.rs:139   main: F:\Cargo\bin\cargo-ndk.exe f:"f:\\temp\\.tmpADw0AH\\triple-linker.exe"
warning: unused manifest key: package.crate-type
   Compiling cfg-if v1.0.0
   Compiling bytes v1.4.0
   Compiling cesu8 v1.1.0
   Compiling jni-sys v0.3.0
   Compiling json v0.12.4
   Compiling memchr v2.5.0
   Compiling thiserror v1.0.40
   Compiling log v0.4.17
   Compiling combine v4.6.6
   Compiling jni v0.21.1
   Compiling flashdrop v0.1.0 (H:\rust\flashdrop)
    Finished dev [unoptimized + debuginfo] target(s) in 5.96s
[2023-05-10T12:54:02Z INFO  cargo_ndk::cli] Copying libraries to ....
[2023-05-10T12:54:02Z ERROR cargo_ndk::cli] No .so files found in path "H:\\rust\\flashdrop\\target\\aarch64-linux-android\\debug"
[2023-05-10T12:54:02Z ERROR cargo_ndk::cli] Did you set the crate-type in Cargo.toml to include 'cdylib'?
[2023-05-10T12:54:02Z ERROR cargo_ndk::cli] For more info, see <https://doc.rust-lang.org/cargo/reference/cargo-targets.html#library>.
```

So wired........

My cargo.toml as follow:

```toml
[package]
name = "flashdrop"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib"]

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
json = "0.12.4"

```

**Comment by TomieAi** [comment]
```c++
PS D:\rustpj\learn> cargo ndk -t armeabi-v7a -t arm64-v8a -o ./jniLibs build --release
[2023-05-10T17:40:17Z INFO  cargo_ndk::cli] Using NDK at path: D:\AndroidSDK\ndk\25.2.9519653 (NDK_HOME)
[2023-05-10T17:40:17Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-05-10T17:40:17Z INFO  cargo_ndk::cli] Building targets: armeabi-v7a, arm64-v8a
[2023-05-10T17:40:17Z INFO  cargo_ndk::cli] Building armeabi-v7a (armv7-linux-androideabi)
   Compiling example v0.1.0 (D:\rustpj\learn)
    Finished release [optimized] target(s) in 0.09s
[2023-05-10T17:40:17Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
   Compiling example v0.1.0 (D:\rustpj\learn)
    Finished release [optimized] target(s) in 0.09s
[2023-05-10T17:40:17Z INFO  cargo_ndk::cli] Copying libraries to ./jniLibs...
[2023-05-10T17:40:17Z ERROR cargo_ndk::cli] No .so files found in path "D:\\rustpj\\learn\\target\\armv7-linux-androideabi\\release"
[2023-05-10T17:40:17Z ERROR cargo_ndk::cli] Did you set the crate-type in Cargo.toml to include 'cdylib'?
[2023-05-10T17:40:17Z ERROR cargo_ndk::cli] For more info, see <https://doc.rust-lang.org/cargo/reference/cargo-targets.html#library>.
PS D:\rustpj\learn> 
```

my cargo.toml is same as the example folder on this repo. 

but doing cargo ndk -t armeabi-v7a build only

```c++
[2023-05-10T17:43:07Z INFO  cargo_ndk::cli] Using NDK at path: D:\AndroidSDK\ndk\25.2.9519653 (NDK_HOME)
[2023-05-10T17:43:07Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-05-10T17:43:07Z INFO  cargo_ndk::cli] Building targets: armeabi-v7a
[2023-05-10T17:43:07Z INFO  cargo_ndk::cli] Building armeabi-v7a (armv7-linux-androideabi)
   Compiling example v0.1.0 (D:\rustpj\learn)
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
```

I dont see any .so output xD
hope soon it get fixed <3

**Comment by TomieAi** [comment]
> @TomieAi @rib try version 3.1.1 and let me know if it now works consistently for you.
omg you are the best xD it works <3 ty

```c++
PS D:\rustpj\learn> cargo ndk -t armeabi-v7a -t arm64-v8a -o ./jniLibs build --release
[2023-05-11T08:58:55Z INFO  cargo_ndk::cli] Using NDK at path: D:\AndroidSDK\ndk\25.2.9519653 (NDK_HOME)
[2023-05-11T08:58:55Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-05-11T08:58:55Z INFO  cargo_ndk::cli] Building targets: armeabi-v7a, arm64-v8a
[2023-05-11T08:58:55Z INFO  cargo_ndk::cli] Building armeabi-v7a (armv7-linux-androideabi)
   Compiling example v0.1.0 (D:\rustpj\learn)
    Finished release [optimized] target(s) in 1.05s
[2023-05-11T08:58:57Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
   Compiling example v0.1.0 (D:\rustpj\learn)
    Finished release [optimized] target(s) in 0.57s
[2023-05-11T08:58:57Z INFO  cargo_ndk::cli] Copying libraries to ./jniLibs...
[2023-05-11T08:58:57Z INFO  cargo_ndk::cli] D:\rustpj\learn\target\armv7-linux-androideabi\release\libexample.so -> ./jniLibs\armeabi-v7a\libexample.so
[2023-05-11T08:58:57Z INFO  cargo_ndk::cli] D:\rustpj\learn\target\aarch64-linux-android\release\libexample.so -> ./jniLibs\arm64-v8a\libexample.so
PS D:\rustpj\learn> 
```

got the .so files lets gooooooooooooooooooo xD

------------

this might be out of the topic but.  since we use android ndk to compile ... how do we pass cxx/c flags. where should i put it?

**Comment by bbqsrc** [comment]
The rules for doing that are the same as with cargo and rustc, cargo ndk still just passes through all the flags as it did before.

**Comment by rubenh2905** [comment]
Love you, worked for me

**Comment by rib** [comment]
> @TomieAi @rib try version 3.1.1 and let me know if it now works consistently for you.

Unfortunately `cargo ndk` still isn't working for me on windows, with a project that does cross compile ok from Linux and also used to work with an older toolchain on windows.

The quoting issue is fixed, yay! (I was seeing an issue with the quoting of a linker script, similar to one of the other reports) but now I'm seeing an issue with the command line apparently being too long.

```
The following warnings were emitted during compilation:

warning: The command line is too long.
warning: Error: Errored with code 1
```

This is the command that it's upset about:

<details>
  <summary>Click me</summary>

  ```
running: "C:\\Users\\Robert\\AppData\\Local\\Temp\\.tmpChFZH3\\cxx.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\include\\common" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\include\\foundation" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\include\\pvd" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\include\\task" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\common\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/common/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\fastxml\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/fastxml/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/filebuf/include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/foundation" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/foundation/include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/foundation/unix" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/ccd" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/common" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/contact" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/convex" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/cooking" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/distance" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/gjk" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/hf" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/intersection" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/mesh" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/pcm" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/geomutils/src/sweep" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/include\\cooking" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevel\\api/include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevel\\common/include/collision" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevel\\common/include/pipeline" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevel\\common/include/utils" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevel/common/src/pipeline" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevel\\software/include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevel/software/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\lowlevelaabb\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowlevelaabb/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\lowleveldynamics\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/lowleveldynamics/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physx/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxcharacterkinematic/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxcooking/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxextensions/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxextensions/src/serialization" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxextensions/src/serialization/Binary" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxextensions/src/serialization\\File" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxextensions/src/serialization/Xml" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxextensions/src/tet" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\physxmetadata/core/include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxmetadata/core/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxmetadata/extensions\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxmetadata/extensions/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxvehicle/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxvehicle/src/physxmetadata\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/physxvehicle/src/physxmetadata/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\pvd\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/pvd/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\scenequery\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/scenequery/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source\\simulationcontroller\\include" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/simulationcontroller/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/task/src" "-I" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx\\pxshared\\include" "-Wall" "-Wextra" "--sysroot=C:\\Users\\Robert\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\toolchains/llvm/prebuilt\\windows-x86_64\\sysroot" "-std=c++14" "-w" "-DANDROID" "-DPX_PHYSX_STATIC_LIB" "-DDISABLE_CUDA_PHYSX" "-DPX_SUPPORT_PVD=1" "-DNDEBUG=1" "-o" "C:\\Users\\Robert\\src\\Embark\\ark\\target\\aarch64-linux-android\\release\\build\\physx-sys-fb5993a469625837\\out\\03f707125f972674-PsFastXml.o" "-c" "C:\\Users\\Robert\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\physx-sys-0.11.1\\physx/physx\\source/fastxml/src\\PsFastXml.cpp"
  ```
</details>

I have some vague recollection that by default windows programs have some really silly limit on the length of commands they can spawn, but I'm not sure off the top of my head what's needed to bump that limit.

**Comment by rib** [comment]
It looks like that command is about 12k, which is > the 8k limit. I'm not quite sure how cargo / rustc overcome that limit though

**Pull request merged**
