### PR TITLE
use `llvm-strip` and `llvm-ar` if the arch-specific-named strip and ar are not present

### LINKED ISSUE #38: NDK 23 missing *-ar tools
I'm getting the following error because NDK 23 doesn't seem to have the *-ar tools available. Using NDK 22 is fine.

`error occurred: Failed to find tool. Is /Users/<user>/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar installed?`

### PR DESCRIPTION
**Pull request by jmesmon**
Should fix #38

### CODE REVIEW

**Comment by bbqsrc** [comment]
Thanks for the contribution. I wonder if we should now also check if the new path exists as well, and if neither do, return an error?

**Comment by jmesmon** [comment]
We could, however:

 - for `ar`: making it a hard error here (where we're choosing to define some env vars), might take something that wouldn't be an issue (say, if the build happens to not require `ar` for some reason) and turn it into a hard error, leading folks to need to write workarounds (like creating a fake ar, or making some symlinks)
 - for `strip`: it seems like we could do this. Though I believe trying to run the command would provide us with a descriptive error (one we need to handle well anyhow)

**Comment by bbqsrc** [comment]
If someone doesn't need `ar`, `cargo-ndk` incidentally working isn't ideal, since it's not going to be a valid NDK in any case if it can't find all the basic pieces from the NDK. I prefer things to break when the environment is proven to not be coherent than accidentally work, had that happen to me enough times to become deeply sad. 😄

**Comment by harryfei** [comment]
Why this closed? We need this PR to work with the  new version NDK.

**Comment by bbqsrc** [comment]
This is closed for the reasons clearly stated in my previous comment. If someone wants to make a PR that achieves the goals of this PR without causing the issues it causes, it will be merged.

**Pull request closed without merging**
